pre-commit:
  parallel: true
  jobs:
    - name: prettier
      run: npx prettier --write --cache --ignore-unknown {staged_files}
      stage_fixed: true

post-merge:
  commands:
    npm-install:
      run: npm install

output:
  - summary
  - failure
